In [78]:
#importing the required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import random


In [66]:

#Reading the csv file
data=pd.read_csv('https://raw.githubusercontent.com/arindm007/CropPredictAC/main/cpdata.csv')
print(data.head(1))


   temperature   humidity        ph    rainfall label
0    20.879744  82.002744  6.502985  202.935536  rice


In [67]:
# max and min of pH
print(data['rainfall'].max())
print(data['rainfall'].min())

397.3153799
20.21126747


In [68]:

#Creating dummy variable for target i.e label
label= pd.get_dummies(data.label).iloc[: , 1:]
data= pd.concat([data,label],axis=1)
data.drop('label', axis=1,inplace=True)
print('The data present in one row of the dataset is')
print(data.head(1))
train=data.iloc[:, 0:4].values
test=data.iloc[: ,4:].values


The data present in one row of the dataset is
   temperature   humidity        ph    rainfall  Black gram  Chickpea  \
0    20.879744  82.002744  6.502985  202.935536           0         0   

   Coconut  Coffee  Cotton  Ground Nut  ...  maize  mango  millet  muskmelon  \
0        0       0       0           0  ...      0      0       0          0   

   orange  papaya  pomegranate  rice  watermelon  wheat  
0       0       0            0     1           0      0  

[1 rows x 34 columns]


In [69]:

#Dividing the data into training and test set
X_train,X_test,y_train,y_test=train_test_split(train,test,test_size=0.3)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [70]:

#Importing Decision Tree classifier
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor()
clf.fit(X_train,y_train)

DecisionTreeRegressor()

In [71]:
#Importing RandomForest classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [72]:
print(X_test)

[[ 0.49626351 -0.53209421  0.7557256   0.82207646]
 [ 0.1677538   0.91158069 -0.04949453 -0.82461396]
 [ 0.76038104  0.20761224 -0.2051624  -0.6025893 ]
 ...
 [-0.06257819  0.57077053 -0.18499882 -0.04928987]
 [ 0.15593111  1.29786205 -0.35790247  1.38569446]
 [ 1.00202098  0.64011705 -0.23908253 -0.70361982]]


In [73]:
#Fitting the classifier into training set

pred=clf.predict(X_test)
yPred = rfc.predict(X_test)


In [74]:

from sklearn.metrics import accuracy_score
# Finding the accuracy of the model
a=accuracy_score(y_test,pred)
print("The accuracy of this model is: ", a*100)


The accuracy of this model is:  89.89247311827957


In [75]:
!pip3 install python-firebase
!pip3 install firebase 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [76]:
print(np.random.uniform(6,8))

7.270767656551552


In [84]:
#Using firebase to import data to be tested
from firebase import firebase
# firebase =firebase.FirebaseApplication('https://cropit-eb156.firebaseio.com/')
firebase =firebase.FirebaseApplication('https://e-krishak-86c3d-default-rtdb.firebaseio.com/')
tp=firebase.get('/Weather Station',None)

ah=tp['Humidity']
print(f"Humidity {ah}")

atemp=tp['Temperature']
print(f"Temperature {atemp}")

pH=np.random.uniform(3,10)
print(f"pH {pH}")

rain=np.random.uniform(15,450)
print(f"Rain {rain}")


l=[]
l.append(ah)
l.append(atemp)
l.append(pH)
l.append(rain)

predictcrop=[l]

# Putting the names of crop in a single list
crops=['wheat','mungbean','Tea','millet','maize','lentil','jute','cofee','cotton','ground nut','peas','rubber','sugarcane','tobacco','kidney beans','moth beans','coconut','blackgram','adzuki beans','pigeon peas','chick peas','banana','grapes','apple','mango','muskmelon','orange','papaya','watermelon','pomegranate']
cr='rice'

#Predicting the crop
predictions = clf.predict(predictcrop)
print(predictions)
count=0
mylist = []
for i in range(0,30):
    print(predictions[0][i])
    if(predictions[0][i]==1):
        c=crops[i]
        count=count+1
       # break;
    else:
      mylist.append(crops[i]);
    i=i+1
if(count==0):
    print('The predicted crop is %s'%cr)
else:
    myRes = random.choice(mylist)
    print('The predicted crop is %s'%myRes)
#Sending the predicted crop to database
cp=firebase.put('/croppredicted','crop',myRes)

Humidity 59.0
Temperature 29.0
pH 8.9753176944642
Rain 140
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  1. 0. 0. 0. 0. 0.]]
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
The predicted crop is blackgram
